# Generated by Django 3.2.11 on 2022-04-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabbo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='original_id',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
