# Generated by Django 3.2.11 on 2022-04-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabbo', '0002_make_fields_bigger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='no_of_employees',
        ),
        migrations.AddField(
            model_name='company',
            name='size',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='company',
            name='url',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
