# Generated by Django 3.2.11 on 2022-04-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabbo', '0003_rename_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='size',
        ),
        migrations.AddField(
            model_name='company',
            name='size_from',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='size_to',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
