# Generated by Django 3.2.11 on 2022-04-17 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grabbo', '0004_add_size_range'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobsalary',
            old_name='amount_currency',
            new_name='currency',
        ),
    ]
