# Generated by Django 3.2.11 on 2022-04-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabbo', '0005_rename_amount_currency_jobsalary_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='seniority',
            field=models.CharField(default='-', max_length=256),
            preserve_default=False,
        ),
    ]
