# Generated by Django 3.2.11 on 2023-01-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabbo', '0009_job_is_blacklisted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_blacklisted',
        ),
        migrations.RemoveField(
            model_name='job',
            name='is_blacklisted',
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Fuck It'), (2, 'Interested'), (3, 'Hyped')], default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Fuck It'), (2, 'Interested'), (3, 'Hyped')], default=0),
        ),
    ]
